theme: jekyll-theme-minimal
title: Sam's homepage
logo: ../images/CMSlogo_outline_color.png
description: |
  A family friendly introduction to my work!
  <br><br>
  <a href="/">Home</a><br>
  <a href="/Physics101/ParticlePhysics">Physics 101</a>
  <a href="/MyAnalysis/Analysis">My Analysis</a><br>
  <br><br>
  <a href="mailto:samantha_sunnarborg@brown.edu">samantha_sunnarborg@brown.edu</a>
