theme: jekyll-theme-minimal
title: Sam's homepage
description: |
  A family friendly introduction to my work!

  [Home](/)

  [My Analysis](/MyAnalysis/Analysis)

  [Particle Physics](/Physics101/ParticlePhysics)


header_pages:
  - index.md
  - MyAnalysis/Analysis.md
  - Physics101/ParticlePhysics.md
